TRAIN:
  ENABLE: True 
  DATASET: kinetics
  BATCH_SIZE: 4
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 10
  AUTO_RESUME: True
DATA:
  PATH_TO_DATA_DIR:  /DCAIOCTO/ModelDataZoo/datasets/AMD_data/classify_New_DB_256_FUND_middle/ # /home/agur/projects/AMD/TimeSformer/k600_csv/ 
  NUM_FRAMES: 38
  SAMPLING_RATE: 6
  TRAIN_JITTER_SCALES: [224, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [1]
TIMESFORMER:
  ATTENTION_TYPE: 'divided_space_time' #'joint_space_time'
SOLVER:
  BASE_LR: 0.005
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 11, 14]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 40
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: vit_base_patch16_224
  NUM_CLASSES: 10
  ARCH: vit
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: False 
  DATASET: kinetics
  BATCH_SIZE: 1
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 3
DATA_LOADER:
  NUM_WORKERS: 1
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
#TRAIN.CHECKPOINT_FILE_PATH: ./checkpoints/TimeSformer_divST_16x16_448_K600.pyth
#TRAIN.FINETUNE: True
