TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 24
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
DATA:
  PATH_TO_DATA_DIR: /DCAIOCTO/ModelDataZoo/datasets/AMD_data/wet_to_dry_classify/ #/DCAIOCTO/ModelDataZoo/datasets/AMD_data/wet_to_dry/  
  NUM_FRAMES: 30
  SAMPLING_RATE: 6
  TRAIN_JITTER_SCALES: [224, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [1]
TIMESFORMER:
  ATTENTION_TYPE: 'divided_space_time' #'joint_space_time'
SOLVER:
  BASE_LR: 0.005
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 8, 15]
  LRS: [0.7, 0.1, 0.01]
  MAX_EPOCH: 35
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-3
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: vit_base_patch16_224
  NUM_CLASSES: 3
  ARCH: vit
  LOSS_FUNC: cross_entropy # mse_loss # l1_loss  weighted softmax, focal loss 
  HEAD_ACT: softmax # sigmoid  
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True 
  DATASET: kinetics
  BATCH_SIZE: 32
  NUM_ENSEMBLE_VIEWS: 3
  NUM_SPATIAL_CROPS: 1
  SAVE_RESULTS_PATH: './test_results.pickle'
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
#TRAIN.CHECKPOINT_FILE_PATH: ./checkpoints/TimeSformer_divST_16x16_448_K600.pyth
#TRAIN.FINETUNE: True
