TRAIN:
  ENABLE: False
  DATASET: kinetics
  BATCH_SIZE: 1
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
DATA:
  PATH_TO_DATA_DIR: /DCAIOCTO/ModelDataZoo/datasets/AMD_data/WIP_vids/ # /DCAIOCTO/ModelDataZoo/datasets/AMD_data/classify_DB_csv_for_inf/ # /home/agur/projects/AMD/TimeSformer/k600_csv/ 
  NUM_FRAMES: 30
  SAMPLING_RATE: 6
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [1]
TIMESFORMER:
  ATTENTION_TYPE: 'divided_space_time' #'joint_space_time'
SOLVER:
  BASE_LR: 0.005
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 12, 22]
  LRS: [0.9, 0.2, 0.02]
  MAX_EPOCH: 25
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: vit_base_patch16_224
  NUM_CLASSES: 5
  ARCH: vit
  LOSS_FUNC: bce_logit # bce # cross_entropy
  CLASSIFY_TYPE: "ordinal_regress" # "classes"  # "regression"
  # HEAD_ACT: sigmoid # linear #softmax # relu #  leakyrelu # gelu
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True 
  DATASET: kinetics
  BATCH_SIZE: 1
  NUM_ENSEMBLE_VIEWS: 3
  NUM_SPATIAL_CROPS: 3
  SAVE_RESULTS_PATH: './test_results.pickle'
  CHECKPOINT_FILE_PATH: /home/agur/projects/AMD/AMD_Timesformer/checkpoints/checkpoint_epoch_00019.pyth  
DATA_LOADER:
  NUM_WORKERS: 1
  PIN_MEMORY: True
NUM_GPUS: 0
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
#TRAIN.CHECKPOINT_FILE_PATH: ./checkpoints/TimeSformer_divST_16x16_448_K600.pyth
#TRAIN.FINETUNE: True
