TRAIN:
  ENABLE: False
  DATASET: kinetics
  BATCH_SIZE: 24
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 2
  AUTO_RESUME: True
DATA:
  PATH_TO_DATA_DIR: /home/agur/projects/AMD/AMD_Timesformer/ # /DCAIOCTO/ModelDataZoo/datasets/AMD_data/classify_DB_csv_1/ # /DCAIOCTO/ModelDataZoo/datasets/AMD_data/AMD_OCT_vids/ #  #  /home/agur/projects/AMD/AMD_Timesformer/to_test/
  NUM_FRAMES: 32
  SAMPLING_RATE: 6
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [1]
TIMESFORMER:
  ATTENTION_TYPE: 'divided_space_time' #'joint_space_time'
  PRETRAINED_MODEL: /home/agur/projects/AMD/AMD_Timesformer/checkpoints/checkpoint_epoch_00014.pyth

SOLVER:
  BASE_LR: 0.005
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 11, 14]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 35
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: vit_base_patch16_224
  NUM_CLASSES: 5
  ARCH: vit
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True 
  DATASET: kinetics
  BATCH_SIZE: 64
  NUM_ENSEMBLE_VIEWS: 5
  NUM_SPATIAL_CROPS: 3
  SAVE_RESULTS_PATH: './test_results.pickle'
  CHECKPOINT_FILE_PATH: /home/agur/projects/AMD/AMD_Timesformer/checkpoints/checkpoint_epoch_00014.pyth
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
#TRAIN.CHECKPOINT_FILE_PATH: ./checkpoints/checkpoint_epoch_00020.pyth
#TRAIN.FINETUNE: True
